### ISSUE TITLE
Support MacOSX

### ISSUE THREAD

**Issue by linkerlin** [VladimirMarkelov/clui#55]
All windows flash all-the-time on my mac os x。

**Comment by VladimirMarkelov** [comment]
I'd love to help but I do not have mac at hand. Does it flash all the time or after pressing keys/mouse move/click?

**Comment by gernest** [comment]
@linkerlin can you please expand?

I'm using a mac, and I just ran the main demo after installation without a problem. How do I reproduce this?

The terminal I'm using is iTerm 2, Im running os x yosemite

**Comment by VladimirMarkelov** [comment]
Because there was no code example (it was not clear what flashes - all my examples or new application), at first I thought that the trouble was redrawing the screen too often. But after some debugging an example I saw that redraw was called only after something changed.
So, I was not able to reproduce. And I did not close the issue in case of some can provide details.

**Comment by VladimirMarkelov** [comment]
#58 is more generic issue - I tried to fix but I do not have a terminal that showed blinking text before the fix to be sure that it works

**Comment by pjebs** [comment]
I haven't tried this project yet but I assume @linkerlin  is referring to this phenomena:

https://github.com/manifoldco/promptui/issues/57
