### ISSUE TITLE
Blinking text in terminal

### ISSUE THREAD

**Issue by jamalsa** [VladimirMarkelov/clui#58]
Currently when I run demos/helloworld.go in my system (ArchLinux x64 with Zsh and Konsole) the border and title of windows is blinking. If we look at termbox documentation (https://godoc.org/github.com/nsf/termbox-go#Attribute):

> And on some terminals applying AttrBold to background may result in blinking text. Use them with caution and test your code on various terminals

If I remove AttrBold in https://github.com/VladimirMarkelov/clui/blob/bc8d838e8696af2c1cd312a5aebe4e76a9d9f196/consts.go#L108-L115 the demo displayed normally.

So I propose to remove AttrBold from the code to avoid this issue in some terminal

**Comment by jamalsa** [comment]
I think this is same issue as #55. But this is not macOS only problem so I dont know if I should close this issue or not.

**Comment by VladimirMarkelov** [comment]
Thank you. It is a good thing to know.
Anyway, I do not think we should remove AttrBold from consts.go - it is no harm in having them there. I'd better remove AttrBold from default theme colors in theme.go and turbovision.theme files. And not just remove 'bold' from themes - some colors should be fixed as well since removing 'bold' makes disabled and enabled widgets look the same. Maybe disabled text attributes should be changed, too.

**Comment by VladimirMarkelov** [comment]
Oh. I missed the point that the trouble is only because a background color is 'bold'. So, we can just remove 'bold' from all background colors in theme.go and *.theme files. And then check if disabled and enabled widgets differ - they have different text colors as well

**Comment by jamalsa** [comment]
Yes that is what I do now. I create a new theme and remove all bold in background colors.
