### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by pjebs** [VladimirMarkelov/clui#66]
![1](https://user-images.githubusercontent.com/5377970/34480146-da23eff8-effe-11e7-91e1-34de80913574.gif)
![2](https://user-images.githubusercontent.com/5377970/34480147-dbb43cc4-effe-11e7-997e-e0be52632171.gif)

**Comment by VladimirMarkelov** [comment]
A dialog does not show after the first click and after the second click it crashes?
I hardly can see the crash output

**Comment by pjebs** [comment]
The editfield doesn't recognise delete key in mac (equivalent to backspace in windows keyboards). This is also the case for the Editfield demo project.

Also, when I check "show password", it should do the opposite and show the password, otherwise mask it.

Also when I click on editfield, it shows nonsense text like: `<32;13;5M[<39;9;5M...`

**Comment by pjebs** [comment]
When I click on editbox or click + hold button down + drag on the editbox, the nonsense text still appears: 
![screen shot 2018-01-09 at 8 15 48 am](https://user-images.githubusercontent.com/5377970/34692757-4fd20850-f515-11e7-8584-abbd5e9a785e.png)

**Comment by pjebs** [comment]
eg `[<32;13;12M[<32`

**Comment by VladimirMarkelov** [comment]
> [<32;13;12M[<32
It looks like it prints out raw ANSI-colored string instead of making the string colored. It maybe some trouble at lower level: in termbox library that my library calls. On Windows it cannot be reproduced because Windows does not use ANSI-codes. I tried on Ubuntu server (without any DE) and failed to reproduce. Unfortunately, I do not have any Mac to investigate it deeper.

**Comment by pjebs** [comment]
How can I help you solve this issue?

**Comment by VladimirMarkelov** [comment]
It looks like that your trouble is as the same as: https://github.com/nsf/termbox-go/issues/120 . It is still opened bug. In this case we should wait for termbox fixes the issue.

**Comment by pjebs** [comment]
Is it possible to disable mouse for editbox? may that will fix the issue.

**Comment by pjebs** [comment]
https://github.com/nsf/termbox-go/issues/132#issuecomment-228552744

**Comment by pjebs** [comment]
https://github.com/nsf/termbox-go/issues/132#issuecomment-228845914

**Comment by VladimirMarkelov** [comment]
I know about that comment. But it is fix in a fork of termbox. In termbox the issue is still opened. I do not want to move to a fork from original repo at this moment - the fork is outdated and the last commit was more than year ago.

**Comment by pjebs** [comment]
what if you detect how long before each character. If the time between character is too fast for any human to type, then ignore it.

**Comment by pjebs** [comment]
Where can I make the adjustment if i want to make a fork of your package?

**Comment by VladimirMarkelov** [comment]
I think you can try to fix it in edit.go at ProcessEvent. At least, you can reproduce, debug, and make a working patch. At my side I can only speculate what to do and whether it helps. 
Another idea: instead of checking an interval between key presses you can just try skipping all key press events after edit's mouse click event for a short time (~50-100ms). It should be easier to implement but it requires that the edit receives mouse click before false key presses.

**Comment by VladimirMarkelov** [comment]
What if I move ProcessEvent to separate file and create one version for OSX and one for other OSes? In this case we can have different Ctrl+C behavior for OSX and you can fix mouse click and false keypresses in this file.
I can separate files quickly.

**Comment by pjebs** [comment]
with build tag at the top?

**Comment by pjebs** [comment]
that would be good

**Comment by pjebs** [comment]
It's definately improved significantly but the when you first click on the edit field, you still get `[` and also when you double-click on edit field you also get `[`

**Comment by pjebs** [comment]
This only happens when the mouse is over the edit control.
Perhaps we treat `[` as a special case. If the char is `[` and the next character comes in quicker than `charInvervalMs`, then we ignore the prior `[`. Otherwise we assume the `[` was due to a keyboard press and print it.

Unfortunately this does require to control to remember state which complicates it.

**Comment by pjebs** [comment]
https://godoc.org/github.com/nsf/termbox-go#Key:

Maybe we can detect `MouseLeft` and then ignore `[` char.

**Comment by VladimirMarkelov** [comment]
From one hand, we can do it. But it won't help if we keep using the current algorithm. Because after we skip '[' the next false key press will be processed by edit control. 
To fix it, I think I have to send mouse events to edit control - and then fix as I proposed earlier: skip all key presses after mouse click during some short time interval. OK, I'll add sending mouse events from window to a control.

**Comment by VladimirMarkelov** [comment]
I added patch for MouseLeft. If it fixes your trouble, I can tag the last commit as version 0.7.0 - since it includes some new features and fixes a annoying issue on OSX

**Comment by pjebs** [comment]
I think you can close this issue. It works quite well. There are some glitches, but only when I deliberately continually double click, mouse drag etc. No actual user would do that.
Well done. It works well.
