### ISSUE TITLE
Dismiss modal window

### ISSUE THREAD

**Issue by pjebs** [VladimirMarkelov/clui#72]
I have a window which I'm showing modally.

How do I programatically close it?

**Comment by pjebs** [comment]
I can see `func (c *Composer) DestroyWindow(view Control)` but I can't obtain a `Composer` object.
Is this the right path?

**Comment by VladimirMarkelov** [comment]
DestroyWindow does not stop an application if you close the last Window.
Try sending event to main loop:
```go
    clui.PutEvent(clui.Event{Type: ui.EventCloseWindow})
```
It should close the active Window and activate the Window under it. If it was the last Window an app should close.

**Comment by pjebs** [comment]
I would like to dismiss a specific window. Not necessarily the active window.
What is `func (c *Composer) DestroyWindow(view Control)` for? Why is it showing in `godoc`?

**Comment by VladimirMarkelov** [comment]
It is not in docs because initially I was not going to make it public - it was a bit low level.  Anyway, if you have more than 1 Window DestroyWindow should work fine.

**Comment by pjebs** [comment]
How do I access it?

**Comment by VladimirMarkelov** [comment]
Modal Windows is usually top level Window. That is why I suggested to use sending event.
In the beginning I did not want to give all access to window management (since in multi-threading app it may be error-prone). If you want to dismiss any Window, I can make composer() function public - it won't be the way that everyone should use. It will be a extra tool to do low-level stuff if you know what you are doing - similar to unsafe blocks in Rust.
If you are OK with public composer function (usage of that function you can see in dialogs.go) I'll make it available for external calls.

**Comment by pjebs** [comment]
Yes please
